// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxO6tQahZjzy5k-K358KjLbt9Qrw6AwM4',
    appId: '1:649936591251:web:605e339cb57ae3195eb066',
    messagingSenderId: '649936591251',
    projectId: 'bnsp-sertifikasi',
    authDomain: 'bnsp-sertifikasi.firebaseapp.com',
    storageBucket: 'bnsp-sertifikasi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPwGhN14poS3MfNee1j7JdT7OJFBTrEaE',
    appId: '1:649936591251:android:32bc3d945b8a86125eb066',
    messagingSenderId: '649936591251',
    projectId: 'bnsp-sertifikasi',
    storageBucket: 'bnsp-sertifikasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUflj8GIW9lsnIJs4GnGW1AvOxg6979iA',
    appId: '1:649936591251:ios:bfdb45a19ed9a7485eb066',
    messagingSenderId: '649936591251',
    projectId: 'bnsp-sertifikasi',
    storageBucket: 'bnsp-sertifikasi.appspot.com',
    iosClientId: '649936591251-nf8vpldcoroshra7tlm0nrdp0m7oeqev.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanBnsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUflj8GIW9lsnIJs4GnGW1AvOxg6979iA',
    appId: '1:649936591251:ios:bfdb45a19ed9a7485eb066',
    messagingSenderId: '649936591251',
    projectId: 'bnsp-sertifikasi',
    storageBucket: 'bnsp-sertifikasi.appspot.com',
    iosClientId: '649936591251-nf8vpldcoroshra7tlm0nrdp0m7oeqev.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanBnsp',
  );
}
